/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cidemo.lib;

public class Library {
    public boolean display() {
        System.out.println("Hello Library");
        return true;
    }
}
